local types = require("watjit.types")
local ctrl = require("watjit.ctrl")
local func = require("watjit.func")
local quote = require("watjit.quote")
local struct = require("watjit.struct")
local array = require("watjit.array")
local union = require("watjit.union")
local tagged_union = require("watjit.tagged_union")
local arena = require("watjit.arena")
local slab = require("watjit.slab")
local lru = require("watjit.lru")
local mem = require("watjit.mem")
local bytes = require("watjit.bytes")
local hashtable = require("watjit.hashtable")
local simd = require("watjit.simd")
local stream = require("watjit.stream")
local iter = require("watjit.iter")
local stream_compile = require("watjit.stream_compile")

return {
    Val = types.Val,
    coerce = types.coerce,
    select = types.select,
    cast = types.cast,
    trunc = types.trunc,
    zext = types.zext,
    sext = types.sext,
    bitcast = types.bitcast,
    i8 = types.i8,
    i16 = types.i16,
    i32 = types.i32,
    i64 = types.i64,
    u8 = types.u8,
    u16 = types.u16,
    u32 = types.u32,
    u64 = types.u64,
    f32 = types.f32,
    f64 = types.f64,
    ptr = types.ptr,
    enum = types.enum,
    let = types.let,
    lets = types.lets,
    view = types.view,
    void = types.void,
    label = ctrl.label,
    block = ctrl.block,
    loop = ctrl.loop,
    br = ctrl.br,
    br_if = ctrl.br_if,
    goto_ = ctrl.goto_,
    for_ = ctrl.for_,
    while_ = ctrl.while_,
    if_ = ctrl.if_,
    switch = ctrl.switch,
    func = func.func,
    fn = func.fn,
    quote_expr = quote.quote_expr,
    quote_block = quote.quote_block,
    import = func.import,
    module = func.module,
    struct = struct,
    array = array,
    union = union,
    tagged_union = tagged_union,
    arena = arena,
    slab = slab,
    lru = lru,
    mem = mem,
    bytes = bytes,
    hashtable = hashtable,
    simd = simd,
    stream = stream,
    iter = iter,
    stream_compile = stream_compile,
    PAGE_SIZE = func.PAGE_SIZE,
    pages_for_bytes = func.pages_for_bytes,
}
